name:  Deploy docker container image to docker hub
on:
  tags:
    - v*.*.*
jobs:
  publish_docker_image:
   runs-on: ubuntu-latest
   steps:
     - name:  login to docker
       uses: docker/login-action@v2.0.0
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
